### ISSUE TITLE
`aem` `aio-aem-events-publish`: Service Account (JWT)  DEPRECATED

### ISSUE THREAD

**Issue by vinicius-silva-compasso** [adobe/aio-lib-java#155]
Hello,

Yesterday, adobe setup a new recommened way to integrate their API's.

Now, Service Account (JWT) are being deprecated and will work until Jan 1, 2025, as stated [here](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/).

Do we have any expectation/roadmap to have support for OAuth Server-to-Server credential in [here](https://github.com/adobe/aio-lib-java/tree/main/aem/core_aem#workspace-configuration)?

Thanks in advance!

**Comment by rperelma** [comment]
@vinicius-silva-compasso yes, we will.  cc: @shikhartanwar

**Comment by vinicius-silva-compasso** [comment]
Thanks @rperelma 

Any idea of estimated date?

**Comment by francoisledroff** [comment]
I created https://github.com/adobe/aio-lib-java/issues/163 to track the work

**Comment by vinicius-silva-compasso** [comment]
Thanks @francoisledroff
