### ISSUE TITLE
Package names are too generic

### ISSUE THREAD

**Issue by bstopp** [adobe/aio-lib-java#47]
All of the packages in these libraries are overly generic with respect to the Adobe domain space, and more qualifications are needed to ensure collisions don't occur when in a shared classloader with other artifacts.

For example:

`Workspace` is rooted at `com.adobe`. 

AIOException is rooted at `com.adobe.exception`

At the least, additional package name of aio should be added to ensure separation and protection from conflicts/collisions. e.g.:

`com.adobe.aio...`

Is it slightly redundant? Yes, but given that large volume of packages within the AEM space exist in the com.adobe space, it would help prevent future issues.

**Comment by francoisledroff** [comment]
agreed ! I'll resolve this asap

**Comment by francoisledroff** [comment]
done
